// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzu1w7auhyM-o1fIxivzC2WnIoRYZtJt4',
    appId: '1:512863634059:web:12a910ff8d5d5f9dba4a8e',
    messagingSenderId: '512863634059',
    projectId: 'pikanda1648',
    authDomain: 'pikanda1648.firebaseapp.com',
    storageBucket: 'pikanda1648.firebasestorage.app',
    measurementId: 'G-Q0S6291ZN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZK7DpyXmbN0xEK8YR0QfwzPgX-oMxArg',
    appId: '1:512863634059:android:a3afff24e389b2dfba4a8e',
    messagingSenderId: '512863634059',
    projectId: 'pikanda1648',
    storageBucket: 'pikanda1648.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6EHSJ1yrt89kva5Z7wf9tiuaDYg0CzC0',
    appId: '1:512863634059:ios:0da9896534d5d67eba4a8e',
    messagingSenderId: '512863634059',
    projectId: 'pikanda1648',
    storageBucket: 'pikanda1648.firebasestorage.app',
    iosBundleId: 'com.ayushprtp.pikanda.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6EHSJ1yrt89kva5Z7wf9tiuaDYg0CzC0',
    appId: '1:512863634059:ios:d62c66c47a9098d2ba4a8e',
    messagingSenderId: '512863634059',
    projectId: 'pikanda1648',
    storageBucket: 'pikanda1648.firebasestorage.app',
    iosBundleId: 'com.ayushprtp.pikanda.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzu1w7auhyM-o1fIxivzC2WnIoRYZtJt4',
    appId: '1:512863634059:web:7a00941aea519d49ba4a8e',
    messagingSenderId: '512863634059',
    projectId: 'pikanda1648',
    authDomain: 'pikanda1648.firebaseapp.com',
    storageBucket: 'pikanda1648.firebasestorage.app',
    measurementId: 'G-WP9KNFB2EG',
  );
}
