// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKWXI5NaYpEptx1VieDvjKp9ecnppSdxA',
    appId: '1:395243212042:web:abbe30be8b7d94caee7ef3',
    messagingSenderId: '395243212042',
    projectId: 'pika-panda',
    authDomain: 'pika-panda.firebaseapp.com',
    storageBucket: 'pika-panda.firebasestorage.app',
    measurementId: 'G-52TF0FTT3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSEFLdAvbDrPb6-Q292f7FqoLCaxDD_Gk',
    appId: '1:395243212042:android:0fe70ce6ff511394ee7ef3',
    messagingSenderId: '395243212042',
    projectId: 'pika-panda',
    storageBucket: 'pika-panda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsdNUgEKzVDTOhQeeV6-j-X4Z9qUnZbQc',
    appId: '1:395243212042:ios:51bebd2003bc18b0ee7ef3',
    messagingSenderId: '395243212042',
    projectId: 'pika-panda',
    storageBucket: 'pika-panda.firebasestorage.app',
    iosBundleId: 'com.ayushprtp.pikanda.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsdNUgEKzVDTOhQeeV6-j-X4Z9qUnZbQc',
    appId: '1:395243212042:ios:3744ef53fe083f83ee7ef3',
    messagingSenderId: '395243212042',
    projectId: 'pika-panda',
    storageBucket: 'pika-panda.firebasestorage.app',
    iosBundleId: 'com.ayushprtp.pikanda.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKWXI5NaYpEptx1VieDvjKp9ecnppSdxA',
    appId: '1:395243212042:web:3b0feaef0273ad99ee7ef3',
    messagingSenderId: '395243212042',
    projectId: 'pika-panda',
    authDomain: 'pika-panda.firebaseapp.com',
    storageBucket: 'pika-panda.firebasestorage.app',
    measurementId: 'G-0ZD94N02FJ',
  );

}